#this is a config file with deployment an service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    # match all the pods with the below matchLabels
    matchLabels:
      app: mongo
  # blue print of the pods is template
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      # creating a pod
      # search mongo on docker hub and fill further details
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password

--- # this allows us to have multiple yaml configs within 1 file

# service configuration
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app.kubernetes.io/name: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017